#!/bin/csh
set module=$1
set tag=$2
switch ( $module )
	case support:
	case configure:
	case utils:
	case documentation:
		set SVN=https://github.com/epics-synApps
		breaksw

	default:
		set SVN=https://github.com/epics-modules
		breaksw

endsw

echo svn cp -m "${tag} tag" ${SVN}/${module}/trunk ${SVN}/${module}/tags/${tag}
svn cp -m "${tag} tag" ${SVN}/${module}/trunk ${SVN}/${module}/tags/${tag}
