#!/usr/bin/csh -e
pushd ..;
cd bitBus1-4;gnumake |& tee build.lst
cd ../ipac-2.2;gnumake |& tee build.lst
cd ../mpf1-6;gnumake |& tee build.lst
cd ../mpfGpib1-3;gnumake |& tee build.lst
cd ../mpfSerial1-2;gnumake |& tee build.lst
cd ../motor4-3;gnumake |& tee build.lst
cd ../std1-1;gnumake |& tee build.lst
cd ../dac128V1-1;gnumake |& tee build.lst
cd ../ipUnidig1-1;gnumake |& tee build.lst
cd ../love1-1;gnumake |& tee build.lst
cd ../mca_5.02;gnumake |& tee build.lst
cd ../ip330_1.02;gnumake |& tee build.lst
cd ../ip1-1;gnumake |& tee build.lst
cd ../xxx;gnumake |& tee build.lst
popd;

