#!/bin/sh
# changePrefix for synApps 5.8
if [ $# -lt 2 ]; then
	printf "%s\n" "usage: changePrefix old new"
	printf "%s\n" "example: changePrefix xxx 1bma"
	exit
fi

old=$1
new=$2
for file in *.cmd*
do
	printf "\r%-50s" "$file"
	doSed "s!/${old}/!/${new}/!g" $file
	doSed "s/${old}:/${new}:/g" $file
	doSed "s/${old}\./${new}./g" $file
	doSed "s/ioc${old}/ioc${new}/g" $file
	doSed "s/${old}Lib/${new}Lib/g" $file
	doSed "s/${old}App/${new}App/g" $file
	doSed "s/=${old}/=${new}/g" $file
	doSed "/dbLoadDatabase/s/${old}/${new}/g" $file
	doSed "/registerRecordDeviceDriver/s/${old}/${new}/g" $file
	doSed "/shellPromptSet/s/${old}/${new}/g" $file
done
for file in *.iocsh
do
	if [ -f ${file} ]; then
		printf "\r%-50s" "$file"
		doSed "s/${old}:/${new}:/g" $file
		doSed "s/${old}\./${new}./g" $file
		doSed "s/ioc${old}/ioc${new}/g" $file
		doSed "s/${old}Lib/${new}Lib/g" $file
		doSed "s/${old}App/${new}App/g" $file
		doSed "s/=${old}/=${new}/g" $file
		doSed "/dbLoadDatabase/s/${old}/${new}/g" $file
		doSed "/registerRecordDeviceDriver/s/${old}/${new}/g" $file
		doSed "/shellPromptSet/s/${old}/${new}/g" $file
	fi
done
for file in auto*.req
do
	printf "\r%-50s" "$file"
	doSed "s/${old}:/${new}:/g" $file
done
for file in *.substitutions
do
	printf "\r%-50s" "$file"
	doSed "s/${old}/${new}/g" $file
	doSed "s/${old}:/${new}:/g" $file
	doSed "s/${old}App/${new}App/g" $file
done
if [ -f *.template ]; then
	for file in *.template
	do
		printf "\r%-50s" "$file"
		doSed "s/${old}:/${new}:/g" $file
	done
fi
if [ -f interp.sav ]; then
	doSed "s/${old}/${new}/g" interp.sav
fi
if [ -f bootParms ]; then
	doSed "s!/${old}/!/${new}/!g" bootParms
	doSed "s/ioc${old}/ioc${new}/g" bootParms
fi
if [ -f run ]; then
	doSed "s/${old}/${new}/g" run
fi
if [ -f in-screen.sh ]; then
	doSed "s/${old}/${new}/g" in-screen.sh
fi
if [ -f "${old}.sh" ]; then
	doSed "s/${old}/${new}/g" ${old}.sh
	mv ${old}.sh ${new}.sh
fi

printf "\r%-50s\n" "Done."
